# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  process_embsi_files:
    cmd: python stages/01_process_embsi_files.py
    deps:
      - resources/embsi
      - stages/01_process_embsi_files.py
    outs:
      - cache/process_embsi_files/dnt.parquet
      - cache/process_embsi_files/reprotox.parquet

  build_zinc: 
    cmd: stages/02_build_zinc.sh
    deps:
      - stages/02_build_zinc.sh
      - download
    outs:
      - raw/zinc.parquet
  filter_zinc_phthalates: 
    cmd: python stages/03_filter_phtalates.py
    deps:
      - stages/03_filter_phtalates.py
      - raw/zinc.parquet
    outs:
      - raw/zinc_phthalates
  harmonize_zinc_phthalates: 
    cmd: python stages/04_add_chemharmony_fields.py
    deps:
      - stages/04_add_chemharmony_fields.py
      - raw/zinc_phthalates
    outs:
      - raw/harmonized_phthalates
