stages:

  make_dvc_pipeline:
    cmd: dvc dag --dot | dot -Tpng -o dvc_pipeline.png
    outs:
      - dvc_pipeline.png

  process_embsi_files:
    cmd: python stages/01_process_embsi_files.py
    deps:
      - resources/embsi
      - stages/01_process_embsi_files.py
    outs:
      - cache/process_embsi_files/dnt.parquet
      - cache/process_embsi_files/reprotox.parquet

  build_phthalates:
    cmd: python stages/02_build_phthalates.py
    deps:
      - stages/02_build_phthalates.py
    outs:
      - cache/zinc_phthalates/zinc_phthalates.parquet

  chemharmony_properties:
    cmd: python stages/03_chemharmony_properties.py
    deps:
      - stages/03_chemharmony_properties.py
      - cache/zinc_phthalates/zinc_phthalates.parquet
    outs:
    - cache/chemarmony_properties/phthalates_chemharmony.parquet

  pubtator_properties:
    cmd: python stages/04_pubtator.py
    deps:
      - stages/04_pubtator.py
      - cache/zinc_phthalates/zinc_phthalates.parquet
    outs:
      - cache/pubtator/phthalates_pubtator.parquet

  visualize_phthalates:
    cmd: python stages/05_visualize_phthalates.py
    deps:
      - stages/05_visualize_phthalates.py
      - cache/zinc_phthalates/zinc_phthalates.parquet
    outs:
      - cache/visualize_phthalates/phthalates_clusters_heatmap.png
      - cache/visualize_phthalates/sampled_molecules_grid.png
  
  model_phthalates:
    cmd: python stages/08_model_phthalates.py
    deps:
      - stages/08_model_phthalates.py
      - cache/zinc_phthalates/zinc_phthalates.parquet
    outs:
      - cache/model_phthalates/batches/:
          persist: true
