name: pdaa
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - comm=0.2.2
  - conda=24.11.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=42.0.5
  - debugpy=1.8.11
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - menuinst=2.1.1
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.4.0
  - packaging=23.2
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.48
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.12
  - pyzmq=26.2.0
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tqdm=4.66.4
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - alembic==1.14.0
      - annotated-types==0.7.0
      - ansicolors==1.1.8
      - anthropic==0.34.2
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - babel==2.16.0
      - backoff==2.2.1
      - bcrypt==4.2.0
      - beautifulsoup4==4.12.3
      - biobricks==0.3.9
      - bleach==6.2.0
      - blinker==1.9.0
      - boto3==1.35.57
      - botocore==1.35.57
      - click==8.1.7
      - cloudpickle==3.1.0
      - cloup==3.0.5
      - coiled==1.60.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask==2024.11.0
      - dask-expr==1.1.17
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - distributed==2024.11.0
      - entrypoints==0.4
      - et-xmlfile==2.0.0
      - fabric==3.2.2
      - faiss-cpu==1.9.0.post1
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - filelock==3.15.4
      - flask==3.1.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gilknocker==0.4.1
      - greenlet==3.1.1
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - hypercorn==0.17.3
      - hyperframe==6.0.1
      - importlib-metadata==8.4.0
      - invoke==2.2.0
      - ipython==8.29.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.5.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsondiff==2.2.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.11.0
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - locket==1.0.0
      - mako==1.3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - msgpack==1.1.0
      - multidict==6.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - numpy==2.0.1
      - openai==1.43.0
      - openpyxl==3.1.5
      - overrides==7.7.0
      - pandas==2.2.3
      - pandasql==0.7.3
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - paramiko==3.5.0
      - partd==1.4.2
      - pillow==11.0.0
      - pip-requirements-parser==32.0.1
      - plantuml==0.3.0
      - plotly==5.24.1
      - priority==2.0.0
      - prometheus-client==0.21.0
      - propcache==0.2.0
      - psutil==6.1.0
      - py4j==0.10.9.7
      - pyarrow==17.0.0
      - pycryptodome==3.20.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pynacl==1.5.0
      - pyparsing==3.2.0
      - pypdf2==3.0.1
      - pyspark==3.5.3
      - python-dotenv==1.0.1
      - python-json-logger==3.2.1
      - pytz==2024.1
      - pyyaml==6.0.2
      - ratelimit==2.2.1
      - rdflib==7.1.1
      - rdflib-sqlalchemy==0.5.4
      - rdkit==2024.3.6
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - s3transfer==0.10.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.16.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==1.4.54
      - starlette==0.41.3
      - tabulate==0.9.0
      - tblib==3.0.0
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.20.0
      - toml==0.10.2
      - toolz==1.0.0
      - tornado==6.4.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2024.1
      - uri-template==1.3.0
      - visidata==3.0.2
      - voila==0.5.8
      - voila-gridstack==0.4.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.17.1
      - zict==3.0.0
      - zipp==3.20.1
      - streamlit==1.41.1